In [7]:
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt

In [4]:
train=pd.read_csv("train.csv",index_col=False)

In [8]:
train_labels=['Hour','Minutes', 'Sensor_alpha', 'Sensor_beta', 'Sensor_gamma', 'Sensor_alpha_plus','Sensor_beta_plus', 'Sensor_gamma_plus']
x=train[train_labels]
y=train['Insect']
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)

In [16]:
model = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets
model.fit(x_train,y_train)

#Predict Output

model.score(x_test,y_test)

0.7806967447173044

In [17]:
y_pred = model.predict(x_test)
aux=confusion_matrix(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[728 152  11]
 [129 553   3]
 [ 57  32  86]]
              precision    recall  f1-score   support

           0       0.80      0.82      0.81       891
           1       0.75      0.81      0.78       685
           2       0.86      0.49      0.63       175

    accuracy                           0.78      1751
   macro avg       0.80      0.71      0.74      1751
weighted avg       0.78      0.78      0.78      1751

